# src/test/resources/application-test.yml
spring:
  datasource:
    url: jdbc:h2:mem:test-point-db;DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
