spring:
  application:
    name: Msa Gateway
  cloud:
    gateway:
      routes:
        - id: product-service
          uri: http://localhost:8082
          predicates:
            - Path=/product-service/**
          filters:
            - StripPrefix=1
            - AddRequestHeader=X-Request-Source,gateway

        - id: order-service
          uri: http://localhost:8083
          predicates:
            - Path=/order-service/**
          filters:
            - StripPrefix=1
            - AddRequestHeader=X-Request-Source,gateway

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    gateway:
      enabled: true