spring:
  application:
    name: Order Service

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: 'jdbc:mysql://localhost:3306/order_db?useSSL=false&serverTimezone=UTC&characterEncoding=UTF-8'
    username: root
    password: 1234
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: false
        show_sql: false

server:
  port: 8083

product-service:
  api-url: http://localhost:8082/api/products

point-service:
  api-url: http://localhost:8084/api/points

logging:
  level:
    root: info

