spring:
  application:
    name: Product Service

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: 'jdbc:mysql://localhost:3306/product_db?useSSL=false&serverTimezone=UTC&characterEncoding=UTF-8'
    username: root
    password: 1234
#    hikari:
#      maximum-pool-size: 20

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
        show_sql: true

server:
  port: 8082
#  tomcat:
#    threads:
#      max: 200