spring:
  application:
    name: Product Service

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: 'jdbc:mysql://localhost:3306/product_db?useSSL=false&serverTimezone=UTC&characterEncoding=UTF-8'
    username: root
    password: 1234
    hikari:
      maximum-pool-size: 100
      minimum-idle: 50
      connection-timeout: 20000
      idle-timeout: 300000
      max-lifetime: 1200000

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

server:
  port: 8082
#  tomcat:
#    threads:
#      max: 200